# Generated by Django 4.2.5 on 2023-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking',
            new_name='UserRanking',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rated_recipes',
            field=models.ManyToManyField(through='recipes.UserRanking', to='recipes.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='userranking',
            unique_together={('user', 'recipe')},
        ),
    ]
